-- Create ingredients table for suggestions
CREATE TABLE IF NOT EXISTS ingredients (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add active_ingredient column to drugs
ALTER TABLE drugs ADD COLUMN IF NOT EXISTS active_ingredient TEXT;

-- Seed initial data
INSERT INTO ingredients (name) VALUES 
('Paracetamol'),
('Amoxicillin'),
('Ibuprofen'),
('Omeprazole'),
('Metformin'),
('Amlodipine'),
('Cefuroxime'),
('Salbutamol'),
('Acid ascorbic (Vitamin C)'),
('Diclofenac'),
('Acetylcysteine'),
('Albendazole'),
('Alendronic acid'),
('Allopurinol'),
('Alprazolam'),
('Amitriptyline'),
('Artemether'),
('Artesunate'),
('Atenolol'),
('Atorvastatin'),
('Azithromycin'),
('Betamethasone'),
('Bisoprolol'),
('Bromhexine'),
('Captopril'),
('Carbamazepine'),
('Cefixime'),
('Ceftriaxone'),
('Celecoxib'),
('Cetirizine'),
('Chlorpheniramine'),
('Ciprofloxacin'),
('Clarithromycin'),
('Clindamycin'),
('Clopidogrel'),
('Clotrimazole'),
('Codeine'),
('Colchicine'),
('Dexamethasone'),
('Diazepam'),
('Digoxin'),
('Domperidone'),
('Enalapril'),
('Erythromycin'),
('Esomeprazole'),
('Ethambutol'),
('Famotidine'),
('Fluconazole'),
('Fluoxetine'),
('Furosemide'),
('Glucosamin'),
('Gliclazide'),
('Glyceryl trinitrat'),
('Haloperidol'),
('Heparin'),
('Hydrochlorothiazide'),
('Hydrocortisone'),
('Hyoscine'),
('Insulin'),
('Iosartan'),
('Isosorbid dinitrat'),
('Itraconazole'),
('Ketoconazole'),
('Lactulose'),
('Lamivudine'),
('Lansoprazole'),
('Levocetirizine'),
('Levodopa'),
('Levofloxacin'),
('Lidocaine'),
('Loperamide'),
('Loratadine'),
('Losartan'),
('Mebendazole'),
('Meloxicam'),
('Methylprednisolone'),
('Metoclopramide'),
('Metronidazole'),
('Nifedipine'),
('Nystatin'),
('Pantoprazole'),
('Penicillin V'),
('Phenobarbital'),
('Pioglitazone'),
('Prednisolone'),
('Promethazine'),
('Quetiapine'),
('Rabeprazole'),
('Ranitidine'),
('Rifampicin'),
('Rosuvastatin'),
('Sertraline'),
('Simvastatin'),
('Spironolactone'),
('Telmisartan'),
('Tetracycline'),
('Theophylline'),
('Valsartan'),
('Verapamil'),
('Warfarin')
ON CONFLICT (name) DO NOTHING;
